name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSEOWD: ${{secrets.PASSWORD}}
    steps:
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"